 




export const courses = [
  {
    id: 1,
    slug: "ssc-cgl",
    title: "SSC CGL",
    img:"https://i.pinimg.com/1200x/ed/57/58/ed57582022b26fc449b9b9a765b9459b.jpg",
    shortTitle: "Staff Selection Commission",
    image: "/images/courses/ssc-cgl.png",
    overview:
      "Complete preparation for SSC CGL with experienced faculty, mock tests, doubt sessions and updated study material.",
    duration: "12 Months",
    batchTiming: "08:00 AM - 10:00 AM",
    fees: "₹18,000",
    eligibility: "Graduate",
    language: "Hindi + English",
    faculty: [
      "Reasoning - Rajesh Sir",
      "Math - Amit Sir",
      "English - Rakesh Sir",
      "GK - Sandeep Sir",
    ],
    syllabus: [
      "Reasoning",
      "Quantitative Aptitude",
      "English",
      "General Awareness",
      "Computer",
    ],
    features: [
      "Daily Live Classes",
      "Weekly Mock Test",
      "Printed Notes",
      "Doubt Sessions",
      "Current Affairs",
    ],
  },

  {
    id: 2,
    slug: "ssc-chsl",
    title: "SSC CHSL",
    img:"https://images.careerindia.com/img/2025/09/ssc-delhi-police-constable-600-1758954139.jpg",
    shortTitle: "Staff Selection Commission",
    image: "/images/courses/ssc-chsl.png",
    overview:
      "Complete preparation for SSC CHSL with concept classes, mock tests and practice papers.",
    duration: "10 Months",
    batchTiming: "09:00 AM - 11:00 AM",
    fees: "₹16,000",
    eligibility: "12th Pass",
    language: "Hindi + English",
    faculty: [
      "Reasoning - Rajesh Sir",
      "Math - Amit Sir",
      "English - Rakesh Sir",
      "GK - Sandeep Sir",
    ],
    syllabus: [
      "Reasoning",
      "Math",
      "English",
      "General Awareness",
    ],
    features: [
      "Daily Practice",
      "Weekly Test",
      "PDF Notes",
      "Current Affairs",
      "Doubt Classes",
    ],
  },

  {
    id: 3,
    slug: "railway",
    img:"https://i.pinimg.com/736x/16/77/7f/16777f947cfe971ec4521318215a185f.jpg",
    title: "Railway",
    shortTitle: "Railway Examinations",
    image: "/images/courses/railway.png",
    overview:
      "Preparation for Railway NTPC, Group D and other Railway examinations.",
    duration: "8 Months",
    batchTiming: "07:00 AM - 09:00 AM",
    fees: "₹15,000",
    eligibility: "10th / 12th / Graduate",
    language: "Hindi + English",
    faculty: [
      "Math - Amit Sir",
      "Reasoning - Rajesh Sir",
      "Science - Vivek Sir",
      "Current Affairs - Sandeep Sir",
    ],
    syllabus: [
      "Mathematics",
      "Reasoning",
      "General Science",
      "Current Affairs",
    ],
    features: [
      "Topic Wise Tests",
      "Weekly Mock Tests",
      "Printed Notes",
      "Doubt Sessions",
      "Daily Practice",
    ],
  },

  {
    id: 4,
    slug: "banking",
    img:"https://i.pinimg.com/1200x/a4/9f/a4/a49fa4a32fee78b08fdd5d0a9777b950.jpg",
    title: "Banking",
    shortTitle: "Banking Examinations",
    image: "/images/courses/banking.png",
    overview:
      "Preparation for IBPS PO, Clerk, SBI PO, RBI Assistant and other Banking exams.",
    duration: "9 Months",
    batchTiming: "04:00 PM - 06:00 PM",
    fees: "₹17,000",
    eligibility: "Graduate",
    language: "Hindi + English",
    faculty: [
      "Reasoning - Rajesh Sir",
      "Quantitative Aptitude - Amit Sir",
      "English - Rakesh Sir",
      "Banking Awareness - Sandeep Sir",
    ],
    syllabus: [
      "Reasoning",
      "Quantitative Aptitude",
      "English Language",
      "Computer Awareness",
      "Banking Awareness",
    ],
    features: [
      "Daily Live Classes",
      "Weekly Mock Tests",
      "Speed Test Series",
      "Interview Guidance",
      "Printed Notes",
      "Current Affairs",
    ],
  },

  {
    id: 5,
    slug: "bpsc",
    img:"https://i.pinimg.com/736x/49/9f/ff/499fff1bd5898adca8174ed5218c3d29.jpg",
    title: "BPSC",
    shortTitle: "Bihar Public Service Commission",
    image: "/images/courses/bpsc.png",
    overview:
      "Complete preparation for BPSC Prelims, Mains and Interview.",
    duration: "15 Months",
    batchTiming: "10:00 AM - 01:00 PM",
    fees: "₹28,000",
    eligibility: "Graduate",
    language: "Hindi + English",
    faculty: [
      "History - Rajesh Sir",
      "Geography - Vivek Sir",
      "Polity - Amit Sir",
      "Economics - Sandeep Sir",
    ],
    syllabus: [
      "History",
      "Geography",
      "Polity",
      "Economics",
      "Current Affairs",
      "CSAT",
    ],
    features: [
      "Answer Writing Practice",
      "Daily Newspaper Analysis",
      "Weekly Test",
      "Interview Guidance",
      "Printed Notes",
    ],
  },

  {
    id: 6,
    slug: "bihar-si",
    title: "Bihar SI",
    img:"https://i.pinimg.com/736x/a4/29/d0/a429d0a5c87524b150bc2e52c4238dde.jpg",
    shortTitle: "Bihar Sub Inspector",
    image: "/images/courses/bihar-si.png",
    overview:
      "Complete preparation for Bihar Police Sub Inspector Examination.",
    duration: "10 Months",
    batchTiming: "03:00 PM - 05:00 PM",
    fees: "₹18,500",
    eligibility: "Graduate",
    language: "Hindi + English",
    faculty: [
      "Math - Amit Sir",
      "Reasoning - Rajesh Sir",
      "GK - Sandeep Sir",
      "Current Affairs - Vivek Sir",
    ],
    syllabus: [
      "Mathematics",
      "Reasoning",
      "General Knowledge",
      "Current Affairs",
    ],
    features: [
      "Physical Guidance",
      "Weekly Mock Test",
      "Printed Notes",
      "Doubt Sessions",
      "Interview Preparation",
    ],
  },

  {
    id: 7,
    slug: "ctet-tre",
    img:"https://images.shiksha.com/mediadata/images/articles/1653393633phphF03nQ.jpeg",
    title: "CTET / TRE",
    shortTitle: "Teaching Examinations",
    image: "/images/courses/ctet.png",
    overview:
      "Complete preparation for CTET, STET and Bihar TRE Teacher Recruitment.",
    duration: "8 Months",
    batchTiming: "05:00 PM - 07:00 PM",
    fees: "₹14,000",
    eligibility: "Graduation + B.Ed / D.El.Ed",
    language: "Hindi + English",
    faculty: [
      "CDP - Neha Ma'am",
      "Hindi - Rajesh Sir",
      "English - Amit Sir",
      "EVS - Vivek Sir",
    ],
    syllabus: [
      "Child Development & Pedagogy",
      "Hindi",
      "English",
      "Mathematics",
      "EVS",
    ],
    features: [
      "Practice Sets",
      "Weekly Mock Test",
      "PDF Notes",
      "Expert Faculty",
      "Doubt Sessions",
    ],
  },
];