export const selectionData = [
  {
    id: 1,
    name: "Rohit Kumar",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    exam: "SSC CGL",
    category: "SSC",
    year: 2023,
    rank: "AIR 45",
    marks: 172,
    post: "Income Tax Inspector",
    state: "Bihar",
    course: "SSC Foundation Batch",
    attempt: 1,
    testimonial: "Success Academy ki wajah se mera selection hua.",
    photoVerified: true,
  },
  {
    id: 2,
    name: "Anjali Kumari",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    exam: "BPSC",
    category: "State PCS",
    year: 2023,
    rank: "Rank 78",
    marks: 895,
    post: "BPSC Officer",
    state: "Bihar",
    course: "BPSC Complete Batch",
    attempt: 2,
    testimonial: "Faculty aur test series bahut helpful thi.",
    photoVerified: true,
  },
  {
    id: 3,
    name: "Vikash Ranjan",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    exam: "SSC CHSL",
    category: "SSC",
    year: 2023,
    rank: "AIR 159",
    marks: 168,
    post: "Data Entry Operator",
    state: "Jharkhand",
    course: "SSC CHSL Batch",
    attempt: 1,
    testimonial: "Mock tests ne confidence badhaya.",
    photoVerified: true,
  },
  {
    id: 4,
    name: "Neha Singh",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    exam: "Bihar SI",
    category: "Police",
    year: 2023,
    rank: "Rank 23",
    marks: 432,
    post: "Sub Inspector",
    state: "Bihar",
    course: "Bihar SI Premium Batch",
    attempt: 1,
    testimonial: "Best faculty aur daily practice set.",
    photoVerified: true,
  },
  {
    id: 5,
    name: "Aman Raj",
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    exam: "RRB NTPC",
    category: "Railway",
    year: 2023,
    rank: "AIR 312",
    marks: 84,
    post: "Commercial Apprentice",
    state: "Uttar Pradesh",
    course: "Railway Complete Batch",
    attempt: 2,
    testimonial: "Teachers ne har doubt clear kiya.",
    photoVerified: true,
  },
  {
    id: 6,
    name: "Priya Sharma",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    exam: "IBPS PO",
    category: "Banking",
    year: 2024,
    rank: "AIR 61",
    marks: 78,
    post: "Probationary Officer",
    state: "Delhi",
    course: "Banking Foundation",
    attempt: 1,
    testimonial: "Interview guidance outstanding thi.",
    photoVerified: true,
  },
  {
    id: 7,
    name: "Rahul Verma",
    image: "https://randomuser.me/api/portraits/men/81.jpg",
    exam: "SBI Clerk",
    category: "Banking",
    year: 2024,
    rank: "AIR 104",
    marks: 82,
    post: "Junior Associate",
    state: "Bihar",
    course: "Banking Crash Course",
    attempt: 2,
    testimonial: "Speed aur accuracy improve hui.",
    photoVerified: true,
  },
  {
    id: 8,
    name: "Pooja Kumari",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
    exam: "CTET",
    category: "Teaching",
    year: 2024,
    rank: "Qualified",
    marks: 122,
    post: "Primary Teacher",
    state: "Bihar",
    course: "CTET Complete Batch",
    attempt: 1,
    testimonial: "Notes aur PYQs bahut useful the.",
    photoVerified: true,
  },
  {
    id: 9,
    name: "Saurabh Kumar",
    image: "https://randomuser.me/api/portraits/men/90.jpg",
    exam: "BPSC TRE",
    category: "Teaching",
    year: 2024,
    rank: "Rank 37",
    marks: 138,
    post: "Government Teacher",
    state: "Bihar",
    course: "TRE Special Batch",
    attempt: 1,
    testimonial: "Best mentorship aur guidance mila.",
    photoVerified: true,
  },
  {
    id: 10,
    name: "Sneha Gupta",
    image: "https://randomuser.me/api/portraits/women/90.jpg",
    exam: "SSC MTS",
    category: "SSC",
    year: 2024,
    rank: "AIR 89",
    marks: 146,
    post: "Multi Tasking Staff",
    state: "Uttar Pradesh",
    course: "SSC MTS Batch",
    attempt: 2,
    testimonial: "Regular practice se selection hua.",
    photoVerified: true,
  },
];