export const topPerformer = [
{
    id: 1,
    name: "Rohit Kumar",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    exam: "SSC CGL",
    category: "SSC",
    year: 2023,
    rank: "AIR 45",
    marks: 172,
    post: "Income Tax Inspector",
    state: "Bihar",
    course: "SSC Foundation Batch",
    attempt: 1,
    testimonial: "Success Academy ki wajah se mera selection hua.",
    photoVerified: true,
  },
  {
    id: 2,
    name: "Anjali Kumari",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    exam: "BPSC",
    category: "State PCS",
    year: 2023,
    rank: "Rank 78",
    marks: 895,
    post: "BPSC Officer",
    state: "Bihar",
    course: "BPSC Complete Batch",
    attempt: 2,
    testimonial: "Faculty aur test series bahut helpful thi.",
    photoVerified: true,
  },
  {
    id: 3,
    name: "Vikash Ranjan",
    image: "https://randomuser.me/api/portraits/men/52.jpg",
    exam: "SSC CHSL",
    category: "SSC",
    year: 2023,
    rank: "AIR 159",
    marks: 168,
    post: "Data Entry Operator",
    state: "Jharkhand",
    course: "SSC CHSL Batch",
    attempt: 1,
    testimonial: "Mock tests ne confidence badhaya.",
    photoVerified: true,
  }
]